# Generated by Django 5.2.7 on 2025-10-20 07:12

import apps.notes.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=apps.notes.models.note_image_upload_path)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('checksum', models.CharField(help_text='SHA256 hash of the image', max_length=64)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ocr_text', models.TextField(blank=True, help_text='Extracted text from OCR')),
                ('object_labels', models.JSONField(default=list, help_text='List of detected objects/labels')),
                ('analysis_error', models.TextField(blank=True, help_text='Error message if analysis failed')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='notes.note')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
